Util eradication
brokenManager/devlaza-back pull request #48
Opened 2020-04-05 11:15 UTC by isso0424

for #36

2020-04-05 11:16 UTC, isso0424 commented
ついでに #41 も実装

2020-04-05 14:16 UTC, mirror-kt requested changes
単一責任の原則が疎かになってる奴がいるぞ

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +fun String.convertToUUID():UUID{
これは慣習ですがconvertはあまりこの場面で使うべき単語ではないので普通に`toUuid`もしくは`toUUID`の方がいい。
```suggestion
fun String.toUUID():UUID{
```

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +package com.approvers.devlazaApi.controller
こいつらはControllerではないのでcontroller以下にあるのはまずい。

```suggestion
package com.approvers.devlazaApi.util
```

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +    return tags.toList()
Listから空文字の要素を除外してるように見える(違ったら多分寝ぼけてる)

```suggestion
    val tags: MutableList<String> = getTags() ?: return listOf()
    
    return tags.filterNot { it.isEmpty() }
```

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +fun TokenRepository.tokenCheck(token: String): Token{
メソッド名は動詞で書きますね
tokenCheckだとcheckは名詞です
```suggestion
fun TokenRepository.checkToken(token: String): Token{
```

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +fun ProjectMemberRepository.getProjectMember(userId: UUID, projectId: UUID): MutableList<ProjectMember>{
Project#getMembers()にすべき
あと戻り値はMutableではないのでListで返すべき

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +    val projectMemberList: List<ProjectMember> =  this.findAll()
`findAll()`は厳禁です
必要なデータだけを取得してください

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +        if (projectId == projectMember.projectId && userId == projectMember.userId) result.add(projectMember)
コードで対応するんじゃなくてクエリの方で絞って

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +    val regex = Regex("\\+")
こいつは何を分岐してるの

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
> +        val projectMember: ProjectMember = projectMemberRepository.getProjectMember(userId, projectId)[0]
[0] is 何

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
>          }
```suggestion
        val recruiting: Int = rawRecruiting.toIntOrNull() ?: 1
```

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    fun getAllSites(): List<Sites> = sitesRepository.findAll()
このエンドポイント要りますか
findAllはできるだけ避けて

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    @PostMapping("/add")
```suggestion
    @PostMapping("/")
```
RESTfulに

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +                            explanation = site[0],
what is site[0]

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +                            url = site[1],
what is site[1]

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    private fun String?.divideToSites(): MutableList<List<String>>{
返す値はMutableですか

```suggestion
    private fun String?.divideToSites(): List<List<String>>{
```

2020-04-05 14:16 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +        return sites
```suggestion
        return this.split("+")
            .map { it.split(",") }
```
Streamぽく書こうね

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +    val regex = Regex("\\+")
+が入ってるかどうかを判定してる
正規表現だからエスケープしてる

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
> +        val projectMember: ProjectMember = projectMemberRepository.getProjectMember(userId, projectId)[0]
返り値がlistだから1番目を取ってる

これListである必要無いね

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
>          }
これでいけるのか

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    fun getAllSites(): List<Sites> = sitesRepository.findAll()
了解

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    @PostMapping("/add")
それは別PRでやる

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +                            explanation = site[0],
ああこれはindexに意味を持たせちゃったせい
Mapに直すわ

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +                            url = site[1],
inde(ry

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    private fun String?.divideToSites(): MutableList<List<String>>{
はい

2020-04-05 14:28 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +        return sites
これでできるんか()

2020-04-05 14:32 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +        return sites
あ、最後にtoMutableListしなきゃいけないな

2020-04-05 14:43 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/ExtendsFunctions.kt
> +fun ProjectMemberRepository.getProjectMember(userId: UUID, projectId: UUID): MutableList<ProjectMember>{
Projectに関連付けるのは別なPRでやる

2020-04-05 15:21 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/SitesController.kt
> +    private fun String?.divideToSites(): MutableList<List<String>>{
いや嘘ですImutableです

2020-04-06 13:27 UTC, mirror-kt approved these changes
LGTM

2020-04-06 13:28 UTC, isso0424 commented
***†MERGE†***

2020-04-06 13:28 UTC, merged