findAllをあれこれした
brokenManager/devlaza-back pull request #57
Opened 2020-04-08 13:36 UTC by isso0424

UserControllerのfindAllを消し飛ばした

ProjectsControllerのfindAllに範囲の指定を設けた

2020-04-08 18:11 UTC, mirror-kt requested changes

2020-04-08 18:11 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
> +        val allProjects: MutableList<Projects> = projectsRepository.findAll().toMutableList()
findAllしとるやんけ

2020-04-08 18:12 UTC, isso0424 commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
> +        val allProjects: MutableList<Projects> = projectsRepository.findAll().toMutableList()
これに関してはBetweenで取る方法が使えなかったからその後でsliceで返す量を絞る実装にしている
idがUUIDだからBetweenで件数指定できないんや...

2020-04-09 13:25 UTC, mirror-kt commented on src/main/kotlin/com/approvers/devlazaApi/controller/ProjectsController.kt
> +        val allProjects: MutableList<Projects> = projectsRepository.findAll().toMutableList()
んじゃいいや

2020-04-09 13:25 UTC, mirror-kt approved these changes

2020-04-09 13:26 UTC, merged